sudo: required
services:
  - docker
before install:
  - docker build -t  lokkesshhh/docker-react -f Dockerfile.dev . 
script:
  - travis_wait docker run lokkesshhh/docker-react npm run test -- --coverage 
