sudo: required
services:
  - docker
before install:
  - docker build -t  lokkesshhh/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true lokkesshhh/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "Docker_react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-ca-central-1-468562082703"
  bucket_path: "Docker_react"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY