sudo: required
services:
  - docker
before install:
  - docker build -t  lokkesshhh/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true lokkesshhh/docker-react npm run test -- --coverage 
